;;; fringe-helper-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from fringe-helper.el

(register-definition-prefixes "fringe-helper" '("fringe-"))

;;; End of scraped data

(provide 'fringe-helper-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fringe-helper-autoloads.el ends here
